---
- hosts: all
  vars:
    sudoers:
      - challenge
  roles: 
    - userSudo          #ROL QUE GENERA EL USUARIO CHALLENGE PASSWORDLESS

- hosts: elasticsearch
  become: true
  vars:
    es_version: 7.6.0
  roles:
    - elastic.elasticsearch
#    - geerlingguy.java  #ROL DE ANSIBLE GALAXY QUE INSTALA JAVA
#    - installES         #ROL QUE INSTALA ELASTICSEARCH

- hosts: logstash
  roles:
    - installDocker     #ROL QUE INSTALA DOCKER SEARCH DIRECTAMENTE EN LA VM

- hosts: kibana
  roles:
    - installDocker     

- hosts: javaspring
  become: true
  roles:
    - geerlingguy.java  
    - installDocker