---
- hosts: all
  vars:
    sudoers:
      - challenge
  roles: 
    - userSudo          #ROL QUE GENERA EL USUARIO CHALLENGE PASSWORDLESS

- hosts: elasticsearch
  become: true
  vars:
    es_version: 7.6.0
  roles:
    - geerlingguy.java  #ROL DE ANSIBLE GALAXY QUE INSTALA JAVA
    - installES         #ROL QUE INSTALA ELASTICSEARCH
  # - elastic.elasticsearch

- hosts: logstash
  roles:
    - installDocker     #ROL QUE INSTALA DOCKER SEARCH DIRECTAMENTE EN LA VM
    - installLogstash

- hosts: kibana
  roles:
    - installDocker
    - installKibana     

- hosts: javaspring
  become: true
  roles:
    - geerlingguy.java  
    - installDocker