---
- hosts: all
  vars:
    sudoers:
      - challenge
  roles: 
    - userSudo  #ROL QUE GENERA EL USUARIO CHALLENGE PASSWORDLESS

- hosts: logstash
  roles:
    - installDocker

- hosts: kibana
  roles:
    - installDocker #ROL QUE INSTALA DOCKER SEARCH DIRECTAMENTE EN LA VM

- hosts: javaspring
  become: true
  roles:
    - geerlingguy.java
    - installDocker